### PR TITLE
Split IsortItem into Item and File implementations

### PR DESCRIPTION
**Pull request by nicoddemus**
This fixes support for pytest 7.0 and is the recommended approach to implement collectors and items.

Close https://github.com/pytest-dev/pytest/issues/9487

### CODE REVIEW

**Comment by nicoddemus** [comment]
Note: we can simplify the code a bit if you are willing to drop support for pytest 4.

**Comment by nicoddemus** [comment]
Some tests failed due to missing "isort" and in support for pytest 4.

(I unfortunately can't `tox` locally because the `tox` configuration is no Windows friendly, that's why I missed that case).

**Comment by stephrdev** [comment]
> Note: we can simplify the code a bit if you are willing to drop support for pytest 4.

Yes that's fine. I'll to a major release then.

**Comment by nicoddemus** [comment]
> Yes that's fine. I'll to a major release then.

That's good, but better do that in a follow up.

**Pull request merged**
